In [1]:
import numpy as np

In [7]:
x = np.array([1,2,3,4,5])
print(x)
print(x.size)
print(x.dtype)
print(x.shape)

[1 2 3 4 5]
5
int32
(5,)


In [10]:
y = np.array(['Hello','World'])
print(y)
print(y.dtype)
print(y.size)
print(y.shape)

['Hello' 'World']
<U5
2
(2,)


In [11]:
x = np.array([1, 2, 'World'])

# We print information about x
print('x = ', x)
print('x has dimensions:', x.shape) 
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x =  ['1' '2' 'World']
x has dimensions: (3,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: <U11


In [13]:
# We create a rank 1 ndarray that contains integers
x = np.array([1,2,3])

# We create a rank 1 ndarray that contains floats
y = np.array([1.0,2.0,3.0])

# We create a rank 1 ndarray that contains integers and floats
z = np.array([1, 2.5, 4])

# We print the dtype of each ndarray
print('The elements in x are of type:', x.dtype)
print('The elements in y are of type:', y.dtype)
print('The elements in z are of type:', z.dtype)
print(x,y,z)

The elements in x are of type: int32
The elements in y are of type: float64
The elements in z are of type: float64
[1 2 3] [1. 2. 3.] [1.  2.5 4. ]


In [15]:
Y = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])

# We print information about Y
print('Y = \n', Y)
print('Y is an object of type:', type(Y))
print('The elements in Y are of type:', Y.dtype)
print('Y has dimensions:', Y.shape)
print('Y has a total of', Y.size, 'elements')

Y = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int32
Y has dimensions: (4, 3)
Y has a total of 12 elements


In [20]:
x = np.array([1,2,3,4,5])
np.save('my_array', x)
y = np.load('my_array.npy')
print(y)

[1 2 3 4 5]


In [25]:
x = np.array([2.2, 4.5, 3.4, 3.6], dtype = np.int64)
print(x.dtype)
print(x)

int64
[2 4 3 3]


In [29]:
x = np.zeros(5, dtype = np.int64)
print(x)

[0 0 0 0 0]


In [35]:
x = np.ones((4,3))
print(x)
print(x.size)
print(x.shape)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
12
(4, 3)


In [36]:
x = np.full((4,3),5)
print(x)

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


In [37]:
x = np.diag([10,20,50])
print(x)

[[10  0  0]
 [ 0 20  0]
 [ 0  0 50]]


In [38]:
x = np.arange(0,20,2)
print(x)

[ 0  2  4  6  8 10 12 14 16 18]


In [44]:
x = np.linspace(0,25,10,endpoint = False)
print(x)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


In [49]:
x = np.random.randint(4,15, (3,2))
print(x)

[[ 9 10]
 [ 8  5]
 [ 7  7]]


In [6]:
x = np.random.normal(0,0.1, size = (1000,1000))
print(x)

[[ 0.27988868  0.29621646  0.06120259 ...  0.07834562  0.00374112
   0.05460639]
 [ 0.03816514 -0.16610592  0.08651033 ... -0.20355022  0.07048734
  -0.33818372]
 [-0.08206004  0.02091043  0.04468799 ... -0.09169479  0.07269304
   0.01169333]
 ...
 [-0.09531485  0.06896783  0.12419987 ... -0.04287556  0.09193854
  -0.01508898]
 [-0.06173691  0.09592954 -0.04787285 ...  0.15013327  0.04958181
   0.10795118]
 [ 0.15257469 -0.0778833  -0.0863149  ...  0.02247301 -0.02011413
   0.1490841 ]]


In [2]:
x = np.array([1,2,3,4,5])


In [3]:
X = np.random.randint(1,20, size=(50,5))
print("Shape of X is: ", X.shape)
print(X)

Shape of X is:  (50, 5)
[[18 19 10  8 13]
 [17  1 14  6 19]
 [ 2  6 11  6 15]
 [10  9 12 12  4]
 [11 14  6  8 11]
 [ 6 16 18  9 12]
 [ 4  3  5  6  7]
 [ 9 13 18  6 15]
 [ 8  9  7  1 13]
 [18 13  7  5 13]
 [12  7 17 17 16]
 [ 5  1 17 19 15]
 [14 16  8 18 12]
 [12  7  1  6 18]
 [10  3 13  9 12]
 [10  1  2 14  8]
 [ 1 19 17  3 18]
 [19 17 11  8 17]
 [17  7 15  7  8]
 [ 8  9  9  5  6]
 [17  4 12  6  5]
 [ 6 17  3  6  3]
 [ 4 18  7 11 18]
 [ 2 15  1 14 19]
 [ 8  1  6 16  2]
 [ 8 19 16  5  4]
 [19  1 16 16 15]
 [15  4  2 16 14]
 [ 4  5 10  3 12]
 [ 6  2  9  3  4]
 [18  4 14 17 15]
 [ 6  4 19 15 13]
 [ 6  4  8 10 11]
 [ 1  7 11 19 17]
 [ 9 11  5  7 11]
 [18 17 15  6 19]
 [18  4  6  3  2]
 [ 9  7  7  7  8]
 [18  6 15  5 13]
 [ 9  2 18  1  6]
 [ 9  7 18  3  1]
 [ 9 18  2 18 17]
 [ 9  1 16  2 17]
 [ 4 16  2  6 14]
 [ 5 10  2 11 16]
 [ 2  3  8 15  4]
 [ 7  9  9 15  5]
 [ 4 11 16 13  8]
 [12 10 18  3 14]
 [ 5 19 18  1 16]]


In [4]:
row_indices = np.random.randint(0,50, size=10)
print("Random 10 indices are: ", row_indices)


Random 10 indices are:  [38 16 18 35 28 15  9 16 20 36]


In [5]:
X_subset = X[row_indices, :]
print(X_subset)

[[18  6 15  5 13]
 [ 1 19 17  3 18]
 [17  7 15  7  8]
 [18 17 15  6 19]
 [ 4  5 10  3 12]
 [10  1  2 14  8]
 [18 13  7  5 13]
 [ 1 19 17  3 18]
 [17  4 12  6  5]
 [18  4  6  3  2]]


In [6]:
X_subset = X[row_indices[4:8], :]
print(X_subset)


[[ 4  5 10  3 12]
 [10  1  2 14  8]
 [18 13  7  5 13]
 [ 1 19 17  3 18]]
